"https://www.{default}/":
  type: upstream
  upstream: "app:http"
  id: "main"
  cache:
    enabled: true
    default_ttl: 300
    cookies:
      - 'be_typo_user'
      - 'fe_typo_user'
      - 'PHPSESSID'
      - 'Typo3InstallTool'
    headers: ['Accept', 'Accept-Language', 'X-Tx-Solr-Iq']
  tls:
    strict_transport_security:
      enabled: true
      include_subdomains: true
      preload: true

"https://{default}/":
  type: redirect
  to: "https://www.{default}/"

# uncomment if multisite
# Site 2
# "https://www.site2.com/":
#   type: upstream
#   upstream: "app:http"
#   id: "site2"
#   cache:
#     enabled: true
#     default_ttl: 300
#     cookies:
#       - 'be_typo_user'
#       - 'fe_typo_user'
#       - 'PHPSESSID'
#       - 'Typo3InstallTool'
#     headers: ['Accept', 'Accept-Language', 'X-Tx-Solr-Iq']

# "https://site2.com/":
#   type: redirect
#   to: "https://www.site2.com/"
