services:

  db:
    container_name: ${COMPOSE_PROJECT_NAME}_db
    image: ${DB_IMAGE}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-1234}
    volumes:
      - db:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  web:
    container_name: ${COMPOSE_PROJECT_NAME}_web
    image: ${WEB_IMAGE}
    env_file:
      - ../../../.env
    volumes:
      # - ../../../public/fileadmin/:/var/www/html/public/fileadmin
      # - ../../../.localconf/:/var/www/html/.localconf
      - type: bind
        source: ../../server/nginx/conf.d/${VIRTUAL_PROTO:-http}/
        target: /etc/nginx/conf.d
      - type: bind
        source: ../../../
        target: /var/www/html
        # read_only: true
      - type: volume
        source: var
        target: /var/www/html/var
      - type: volume
        source: typo3temp
        target: /var/www/html/public/typo3temp
      - type: volume
        source: nproxy_certs
        target: /etc/nginx/certs

  solr:
    container_name: ${COMPOSE_PROJECT_NAME}_solr
    image: ${SOLR_IMAGE}
    environment:
      - VIRTUAL_HOST=solr.${VIRTUAL_HOST_1}
    volumes:
      - type: volume
        source: solr
        target: /var/solr

networks:
  default:
    name: nproxy

volumes:
  typo3temp:
    name: ${COMPOSE_PROJECT_NAME}_typo3temp
  var:
    name: ${COMPOSE_PROJECT_NAME}_var
  db:
    name: ${COMPOSE_PROJECT_NAME}_db
  solr:
    name: ${COMPOSE_PROJECT_NAME}_solr
  nproxy_certs:
    external: true
