version: "3.8"

services:

  web:
    container_name: composer
    image: ${WEB_IMAGE}
    env_file:
      - ./.env
    volumes:
      - ${SSH_AUTH_SOCK_VOL:-.}:${SSH_AUTH_SOCK_VOL:-/tmp/}
      - type: bind
        source: ../../
        target: /var/www/html
