base: '%env(PLATFORM_ROUTES_SITE2)%'
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: English
    hreflang: en-us
    direction: ltr
    flag: us
    websiteTitle: ''
    solr_core_read: '%env(SOLR_CORE_EN)%'
rootPageId: 74
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    map:
      sitemap.xml: 1533906435
      yoast-snippetpreview.json: 1480321830
routes:
  -
    route: robots.txt
    type: staticText
    content: "User-agent: *\r\n\r\nDisallow: /typo3/\r\nDisallow: /typo3conf/\r\nAllow: /typo3conf/ext/\r\n\r\n# sitemap\r\nSitemap: %env(PLATFORM_ROUTES_SITE2)%/sitemap.xml"
  -
    route: humans.txt
    type: staticText
    content: "/* SITE */\r\nSite: https://github.com/t3kit\r\nStandards: HTML5, CSS3, PHP7\r\nComponents: TYPO3 v11, t3kit11, Bootstrap 5"
solr_enabled_read: false
solr_host_read: '%env(SOLR_HOST_SITE2)%'
solr_path_read: /solr/
solr_port_read: '%env(SOLR_PORT)%'
solr_scheme_read: http
solr_use_write_connection: false
theme: t3kit
websiteTitle: 'Site 2'
