name: Check t3kit Coding Guidelines
# https://github.com/t3kit/.github/blob/master/CONTRIBUTING.md#coding-rules

on: [push, pull_request]

jobs:
  build:

    name: Greeting

    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: File list
        run: ls -la

      - name: Install composer
        uses: docker://composer:1.9
        with:
          args: "install"

      - name: Lint
        uses: docker://composer:1.9
        with:
          args: "lint"

      - name: Echo the greeting's time
        run: echo 'Done'
