name: Check t3kit Coding Guidelines
# https://github.com/t3kit/.github/blob/master/CONTRIBUTING.md#coding-rules

on: [push, pull_request]

jobs:
  build:

    name: Greeting

    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: File list
        run: ls -la

      - name: Install composer
        uses: docker://composer:1.9
        with:
          args: "install"

      - name: Lint
        uses: docker://composer:1.9
        with:
          args: "run-script lint"

      - name: Docker ps
        run: docker ps -a

      - name: Docker ps
        run: docker-compose ps

      - run: docker network create nproxy

      - run: docker run -d -p=80:80 --name=nproxy --network=nproxy -v=/var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy

      - name: Build the stack
        run: docker-compose up -d

      - name: Docker ps
        run: docker-compose ps

      - name: Echo the greeting's time
        run: echo 'Done'
